spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          group: logMessageConsumers
        output:
          destination: queue.pretty.log.messages
          group: logMessageSent
#      function:
#        definition: uppercase1|sendPreetyMessage


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /